<?php

namespace Database\Seeders;

use App\Models\Animal;
use App\Models\AnimalPhoto;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnimalSeeder extends Seeder
{
    public function run()
    {
       DB::statement('SET FOREIGN_KEY_CHECKS=0;');

      DB::table('animal_photos')->truncate();
      DB::table('animals')->truncate();

      DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    $animalsData = $this->getFullAnimalsList();

        foreach ($animalsData as $data) {
            $animal = Animal::create($data);

            // إضافة 1 أو 2 صورة لكل حيوان
            $photoCount = rand(1, 2);
            for ($i = 1; $i <= $photoCount; $i++) {
                AnimalPhoto::create([
                    'animal_id'   => $animal->id,
                    'photo_url'   => "animals/{$animal->id}/photo{$i}.jpg",
                    'is_main'     => $i === 1,
                    'order_number'=> $i,
                ]);
            }
        }

        $this->command->info('✅ تم إنشاء 30 حيوان مع صورهم بنجاح!');
    }


   private function getFullAnimalsList()
{
    return [

        // ====================== DOGS ======================
        [
            'name' => 'Rocky',
            'type' => 'dog',
            'gender' => 'male',
            'age' => 2,
            'size' => 'medium',
            'weight' => 15.50,
            'description' => 'A friendly Labrador dog that loves playing with children.',
            'story' => 'He was rescued from the street after suffering a minor accident and has fully recovered.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5138,
            'longitude' => 36.2765,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Max',
            'type' => 'dog',
            'gender' => 'male',
            'age' => 4,
            'size' => 'large',
            'weight' => 28.0,
            'description' => 'An intelligent German Shepherd with excellent manners.',
            'story' => 'He previously lived with a family and is now looking for a loving forever home.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => false,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5100,
            'longitude' => 36.2800,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Bella',
            'type' => 'dog',
            'gender' => 'female',
            'age' => 3,
            'size' => 'small',
            'weight' => 8.5,
            'description' => 'A smart and cheerful Poodle with a playful personality.',
            'story' => 'She was returned after a previous adoption and deserves a second chance.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5180,
            'longitude' => 36.2720,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Tommy',
            'type' => 'dog',
            'gender' => 'male',
            'age' => 1,
            'size' => 'medium',
            'weight' => 12.0,
            'description' => 'A friendly Golden Retriever puppy who enjoys meeting new people.',
            'story' => 'He was found wandering in a rural area and brought to safety.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5150,
            'longitude' => 36.2780,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Luna',
            'type' => 'dog',
            'gender' => 'female',
            'age' => 5,
            'size' => 'large',
            'weight' => 22.0,
            'description' => 'A beautiful Siberian Husky with bright blue eyes.',
            'story' => 'She was rescued from an abandoned farm and is ready for a fresh start.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'pending',
            'is_urgent' => false,
            'latitude' => 33.5120,
            'longitude' => 36.2740,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Charlie',
            'type' => 'dog',
            'gender' => 'male',
            'age' => 3,
            'size' => 'medium',
            'weight' => 18.0,
            'description' => 'A playful Labrador who enjoys outdoor activities.',
            'story' => 'He was rescued from a local shelter and is looking for a forever family.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5125,
            'longitude' => 36.2775,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        // ====================== CATS ======================
        [
            'name' => 'Coco',
            'type' => 'cat',
            'gender' => 'female',
            'age' => 3,
            'size' => 'small',
            'weight' => 3.8,
            'description' => 'A calm Persian cat with beautiful long white fur. She enjoys quiet places and gentle cuddles.',
            'story' => 'She was abandoned by her previous owners and rescued.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5102,
            'longitude' => 36.2845,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Lucy',
            'type' => 'cat',
            'gender' => 'female',
            'age' => 1,
            'size' => 'small',
            'weight' => 3.20,
            'description' => 'A calm Persian cat looking for a loving forever home.',
            'story' => 'She was abandoned by her previous owners.',
            'health_status' => 'recovering',
            'is_vaccinated' => true,
            'is_neutered' => false,
            'availability_status' => 'available',
            'is_urgent' => true,
            'latitude' => 33.5102,
            'longitude' => 36.2845,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Misho',
            'type' => 'cat',
            'gender' => 'male',
            'age' => 2,
            'size' => 'small',
            'weight' => 4.1,
            'description' => 'A curious and playful Siamese cat.',
            'story' => 'He was rescued from the rooftop of an old building.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5140,
            'longitude' => 36.2750,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Mimi',
            'type' => 'cat',
            'gender' => 'female',
            'age' => 3,
            'size' => 'small',
            'weight' => 3.5,
            'description' => 'A calm British Shorthair cat with a gentle personality.',
            'story' => 'She was raised as a house cat but lost her home.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5160,
            'longitude' => 36.2730,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Zozo',
            'type' => 'cat',
            'gender' => 'female',
            'age' => 4,
            'size' => 'small',
            'weight' => 4.0,
            'description' => 'A sweet senior cat that enjoys affection and quiet places.',
            'story' => 'She lived with an elderly woman who sadly passed away.',
            'health_status' => 'recovering',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => true,
            'latitude' => 33.5170,
            'longitude' => 36.2740,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Cherry',
            'type' => 'cat',
            'gender' => 'female',
            'age' => 2,
            'size' => 'small',
            'weight' => 3.8,
            'description' => 'A beautiful Calico cat with colorful fur.',
            'story' => 'She was discovered alone in a narrow alley.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5135,
            'longitude' => 36.2760,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        // ====================== BIRDS ======================
        [
            'name' => 'Tweety',
            'type' => 'bird',
            'gender' => 'male',
            'age' => 1,
            'size' => 'small',
            'weight' => 0.15,
            'description' => 'An intelligent African Grey parrot that loves interacting with people.',
            'story' => 'He was abandoned by his previous owner.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => false,
            'availability_status' => 'available',
            'is_urgent' => true,
            'latitude' => 33.5150,
            'longitude' => 36.2750,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Kiki',
            'type' => 'bird',
            'gender' => 'female',
            'age' => 2,
            'size' => 'small',
            'weight' => 0.12,
            'description' => 'A cheerful canary with a beautiful singing voice.',
            'story' => 'She was discovered inside an abandoned cage.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => false,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5110,
            'longitude' => 36.2770,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Nono',
            'type' => 'bird',
            'gender' => 'female',
            'age' => 1,
            'size' => 'small',
            'weight' => 0.08,
            'description' => 'A graceful white pigeon with a gentle personality.',
            'story' => 'She was rescued after suffering a wing injury.',
            'health_status' => 'recovering',
            'is_vaccinated' => true,
            'is_neutered' => false,
            'availability_status' => 'available',
            'is_urgent' => true,
            'latitude' => 33.5165,
            'longitude' => 36.2735,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        // ====================== إضافات إضافية (حسب طلبك) ======================
        [
            'name' => 'Luna',
            'type' => 'cat',
            'gender' => 'female',
            'age' => 2,
            'size' => 'small',
            'weight' => 3.5,
            'description' => 'Curious and playful Siamese cat with bright blue eyes.',
            'story' => 'She was rescued from the street.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5120,
            'longitude' => 36.2800,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'name' => 'Rocky',
            'type' => 'dog',
            'gender' => 'male',
            'age' => 5,
            'size' => 'large',
            'weight' => 35,
            'description' => 'Loyal and intelligent German Shepherd.',
            'story' => 'Well-trained and protective dog.',
            'health_status' => 'healthy',
            'is_vaccinated' => true,
            'is_neutered' => true,
            'availability_status' => 'available',
            'is_urgent' => false,
            'latitude' => 33.5130,
            'longitude' => 36.2750,
            'vet_id' => null,
            'rescue_report_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ];

}
}
